In [2]:
import talib as ta
import os
import matplotlib.pyplot as plt
import mplfinance as mpf
import pandas as pd
import numpy as np
# abspath = os.path.abspath(__file__)
# dname = os.path.dirname(abspath)
# os.chdir(dname)
data_pairs = pd.read_pickle("data_pairs2.pkl")
pairs = pd.read_pickle("pairs2.pkl")

In [9]:
pd.set_option('display.max_rows', Buy_WMA60.shape[0]+1)

Buy_WMA60

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67     True
68    False
69    False
70    False
71    False
72    False
73    False
74     True
75    False
76    False
77    False
dtype: bool

In [128]:
import requests
import pandas as pd
url = "https://api.nobitex.ir/v2/orderbook/all"

payload={}
files={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload, files=files)

s=response.json()
symbol=list(s.keys())
symbol.remove('status')
symbol

['BTCIRT',
 'ETHIRT',
 'LTCIRT',
 'USDTIRT',
 'XRPIRT',
 'BCHIRT',
 'BNBIRT',
 'EOSIRT',
 'XLMIRT',
 'ETCIRT',
 'TRXIRT',
 'DOGEIRT',
 'UNIIRT',
 'DAIIRT',
 'LINKIRT',
 'DOTIRT',
 'AAVEIRT',
 'ADAIRT',
 'SHIBIRT',
 'SOLIRT',
 'MATICIRT',
 'FTMIRT',
 'BTCUSDT',
 'ETHUSDT',
 'LTCUSDT',
 'XRPUSDT',
 'BCHUSDT',
 'BNBUSDT',
 'EOSUSDT',
 'XLMUSDT',
 'ETCUSDT',
 'TRXUSDT',
 'PMNUSDT',
 'DOGEUSDT',
 'UNIUSDT',
 'DAIUSDT',
 'LINKUSDT',
 'DOTUSDT',
 'AAVEUSDT',
 'ADAUSDT',
 'SHIBUSDT',
 'SOLUSDT',
 'MATICUSDT',
 'FTMUSDT']

In [19]:
import pandas as pd
import time
import datetime
import requests
def historicnobitex(symbol,timeframe,fromdate,todate):
        symbol     =  symbol
        tf         =  {'1h':'60','3h':'180','6h':'360','12h':'720','1d':'D','2d':'2D','3d':'3D'}
        duration   =  tf[timeframe]
        fromdate   =  int(time.mktime(datetime.datetime.strptime(fromdate, "%d/%m/%Y").timetuple()))
        todate     =  int(time.mktime(datetime.datetime.strptime(todate, "%d/%m/%Y").timetuple()))
        url = "https://api.nobitex.ir/market/udf/history?symbol=%s&resolution=%s&from=%s&to=%s" % (symbol,duration,fromdate,todate)

        payload={}
        headers = {}

        response = requests.request("GET", url, headers=headers, data=payload)

        df=response.json()

        t=df['t']
        df=pd.DataFrame(df)
        df.columns = ['s','dateTime','close','open','high','low', 'volume']
        df['dateTime'] = pd.to_datetime(df.dateTime, unit='s')
        df['date'] = df.dateTime.dt.strftime("%d/%m/%Y")
        df['time-utc'] = df.dateTime.dt.strftime("%H:%M:%S")
        df.drop(['s','dateTime'], inplace=True, axis=1)

        column_names = ["date", "time-utc", "open", "high", "low", "close", "volume"]
        df = df.reindex(columns=column_names)
        
        return df


symbol    =  'BTCIRT'
timeframe =  '1h'
fromdate  =  '19/03/2022'
todate    =  '25/03/2022'



df = historicnobitex(symbol,timeframe,fromdate,todate)
df=df.astype({'open': 'int64', 'high': 'int64', 'low': 'int64', 'close': 'int64', 'volume': 'float'})
pd.set_option('display.max_row', df.shape[0]+1)
#df[{'open','high'}]=df[{'open','high'}].astype('int64')
df
# t=df['t']
# df=pd.DataFrame(df)
# df.columns = ['s','dateTime','close','open','high','low', 'volume']
# df['dateTime'] = pd.to_datetime(df.dateTime, unit='s')
# df['date'] = df.dateTime.dt.strftime("%d/%m/%Y")
# df['time-utc'] = df.dateTime.dt.strftime("%H:%M:%S")
# df.drop(['s','dateTime'], inplace=True, axis=1)

# column_names = ["date", "time-utc", "open", "high", "low", "close", "volume"]
# df = df.reindex(columns=column_names)

,date,time-utc,open,high,low,close,volume
0,18/03/2022,19:30:00,1071600000,1084919600,1069497820,1075500001,10.609726
1,18/03/2022,20:30:00,1077909960,1078000000,1068779070,1070000000,4.636907
2,18/03/2022,21:30:00,1068779070,1075000000,1064700283,1065800401,4.559982
3,18/03/2022,22:30:00,1068000000,1075000000,1064922470,1074999900,1.948204
4,18/03/2022,23:30:00,1070000400,1074000000,1066000000,1068700800,0.765653
5,19/03/2022,00:30:00,1068700800,1072800000,1064700283,1069001000,0.568390
6,19/03/2022,01:30:00,1069001000,1072000000,1066888880,1066890001,0.418035
7,19/03/2022,02:30:00,1068382623,1071000000,1066890001,1068580001,0.490234
8,19/03/2022,03:30:00,1069000000,1070999900,1066700000,1070990000,1.402938
9,19/03/2022,04:30:00,1070999000,1072100000,1067000001,1067000202,1.768316
10,19/03/2022,05:30:00,1068000000,1070399700,1066600023,1066600023,0.835593
11,19/03/2022,06:30:00,1066600023,1068599580,1061990000,1062000080,2.589782
12,19/03/2022,07:30:00,1062000080,1066935777,1060000000,1064300905,4.363365
13,19/03/2022,08:30:00,1064200888,1069800800,1060956000,1067000000,2.933635
14,19/03/2022,09:30:00,1066560000,1072788770,1064520900,1068488001,2.074497
15,19/03/2022,10:30:00,1068488001,1071000000,1065001299,1069511232,1.190037
16,19/03/2022,11:30:00,1069700000,1072000000,1066000100,1070990000,2.507254
17,19/03/2022,12:30:00,1067200000,1075000000,1067200000,1075000000,2.423982
18,19/03/2022,13:30:00,1073600000,1075760000,1070000000,1071000000,2.109244
19,19/03/2022,14:30:00,1071000000,1075000000,1071000000,1073811570,2.656413
20,19/03/2022,15:30:00,1073811600,1079000000,1071238115,1072000000,3.978014
21,19/03/2022,16:30:00,1071238118,1074999500,1066330200,1067000000,2.960128
22,19/03/2022,17:30:00,1067000000,1069699891,1066071998,1068999300,1.521797
23,19/03/2022,18:30:00,1068000001,1074499999,1067999810,1070500100,1.192041
24,19/03/2022,19:30:00,1070500100,1074346970,1070500000,1072400000,2.706141
25,19/03/2022,20:30:00,1073999499,1082834870,1072400200,1082000020,6.528325
26,19/03/2022,21:30:00,1082000020,1082998994,1070918511,1074236094,4.397622
27,19/03/2022,22:30:00,1075000000,1081999799,1074236694,1078340602,1.486121
28,19/03/2022,23:30:00,1078360000,1081999799,1077990000,1078205000,0.864467
29,20/03/2022,00:30:00,1078200000,1080800000,1075000000,1079899987,0.869274
30,20/03/2022,01:30:00,1075102000,1080000000,1074600000,1076000000,0.483894
31,20/03/2022,02:30:00,1076000000,1080000000,1072000000,1073663202,1.201136
32,20/03/2022,03:30:00,1076858365,1079000000,1072000002,1076899300,0.951083
33,20/03/2022,04:30:00,1076899300,1076900000,1073350222,1073700003,0.886547
34,20/03/2022,05:30:00,1074000000,1076900000,1073400506,1076899400,0.793802
35,20/03/2022,06:30:00,1076899400,1079899000,1074030001,1075400002,0.714463
36,20/03/2022,07:30:00,1075400002,1078998888,1075400001,1076000000,1.071237
37,20/03/2022,08:30:00,1075593149,1078799900,1075592049,1077499900,1.042263
38,20/03/2022,09:30:00,1077499900,1079789000,1075500000,1075600100,2.005373
39,20/03/2022,10:30:00,1076709860,1077000000,1075000121,1075176099,1.552194
40,20/03/2022,11:30:00,1075000121,1076796783,1066000000,1069000503,3.204121
41,20/03/2022,12:30:00,1069500911,1075899975,1068000000,1068000000,1.506348
42,20/03/2022,13:30:00,1068000100,1070090000,1067999999,1069999999,1.384811
43,20/03/2022,14:30:00,1069999999,1071000000,1066730000,1066730000,1.169443
44,20/03/2022,15:30:00,1066730000,1066743100,1063000987,1064000100,1.762387
45,20/03/2022,16:30:00,1064000900,1073000000,1064000100,1066044000,1.522790
46,20/03/2022,17:30:00,1064564401,1066043000,1060000000,1062499000,3.126925
47,20/03/2022,18:30:00,1062499000,1066499900,1060009009,1066499900,1.373697
48,20/03/2022,19:30:00,1067000000,1078000000,1066499900,1076900000,3.650711
49,20/03/2022,20:30:00,1076102800,1076899999,1066500999,1071999700,2.503682
50,20/03/2022,21:30:00,1072000000,1072700000,1067000001,1067000001,1.341297
51,20/03/2022,22:30:00,1067100001,1072000000,1066790892,1068200000,0.810618
52,20/03/2022,23:30:00,1068200001,1072000000,1067551150,1070000000,0.264510
53,21/03/2022,00:30:00,1071890000,1073990000,1068500100,1068850255,0.468392
54,21/03/2022,01:30:00,1068860000,1073490000,1067551850,1067710128,0.854440
55,21/03/2022,02:30:00,1067710129,1067710129,1056000000,1062000000,2.717377
56,21/03/2022,03:30:00,1063700000,1067000000,1061000000,1062100001,0.405919
57,21/03/2022,04:30:00,1062670000,1067000000,1062670000,1063500000,0.724071
58,21/03/2022,05:30:00,1066999799,1068339835,1063999800,1064000001,0.952858
59,21/03/2022,06:30:00,1064000001,1066666666,1063000000,1064600100,1.188899
60,21/03/2022,07:30:00,1064600100,1073000000,1064600000,1070000200,1.642359
61,21/03/2022,08:30:00,1072000000,1072000000,1065000007,1070000000,1.690951
62,21/03/2022,09:30:00,1069093178,1075000000,1066199614,1071000111,1.779577
63,21/03/2022,10:30:00,1069100802,1071900915,1069100801,1070002100,0.924382
64,21/03/2022,11:30:00,1070771818,1072899600,1069700000,1069700000,1.132038
65,21/03/2022,12:30:00,1069700109,1073200000,1065499999,1070500900,2.236398
66,21/03/2022,13:30:00,1070491121,1072999900,1065000000,1065300000,2.126759
67,21/03/2022,14:30:00,1068679665,1071009969,1065000000,1066800900,2.947063
68,21/03/2022,15:30:00,1067001000,1071998000,1066800900,1070000000,1.698440
69,21/03/2022,16:30:00,1068090100,1069000000,1064220000,1067900000,1.443254
70,21/03/2022,17:30:00,1067900000,1070989500,1066002500,1069999600,1.043472
71,21/03/2022,18:30:00,1069999650,1069999999,1067000000,1068900000,0.637351
72,21/03/2022,19:30:00,1068900000,1071000000,1067810100,1070788000,1.471678
73,21/03/2022,20:30:00,1068000001,1068000001,1068000001,1068000001,0.000000
74,21/03/2022,21:30:00,1068000001,1071300000,1067900400,1070000001,0.920773
75,21/03/2022,22:30:00,1070000001,1074444455,1067300000,1072000000,2.182044
76,21/03/2022,23:30:00,1070515000,1072999999,1068316633,1068615501,0.534006
77,22/03/2022,00:30:00,1068316633,1072998787,1068316633,1071851090,0.245405
78,22/03/2022,01:30:00,1070226559,1072300000,1068400001,1070000000,0.106389
79,22/03/2022,02:30:00,1070085400,1080000000,1068500003,1080000000,6.722191
80,22/03/2022,03:30:00,1079999998,1088000000,1073250000,1087999998,7.761919
81,22/03/2022,04:30:00,1087999996,1109999990,1079000000,1108000000,8.529347
82,22/03/2022,05:30:00,1105000101,1115000000,1091000004,1102000000,11.385220
83,22/03/2022,06:30:00,1102000000,1107000000,1080300000,1090000000,6.714998
84,22/03/2022,07:30:00,1086231081,1094887988,1085062327,1091500022,3.668330
85,22/03/2022,08:30:00,1091500022,1100000000,1090350000,1096999900,2.829253
86,22/03/2022,09:30:00,1096100000,1106999900,1096050000,1098213100,5.555974
87,22/03/2022,10:30:00,1098213100,1104000000,1091300100,1103900000,3.357521
88,22/03/2022,11:30:00,1103900000,1108797980,1100300510,1108797980,4.326473
89,22/03/2022,12:30:00,1108797980,1109635000,1102000000,1105100000,2.942287
90,22/03/2022,13:30:00,1105100000,1108499899,1102000001,1104238076,2.462317
91,22/03/2022,14:30:00,1104238076,1108999999,1102500000,1105000009,2.471298
92,22/03/2022,15:30:00,1105000009,1110000000,1102491802,1103600497,2.380389
93,22/03/2022,16:30:00,1103600497,1104800000,1095000000,1096000000,2.302468
94,22/03/2022,17:30:00,1096000000,1102000000,1095100000,1100095001,1.436155
95,22/03/2022,18:30:00,1100095001,1103669900,1100000000,1102520000,0.924623
96,22/03/2022,19:30:00,1103500570,1104849900,1100000000,1102600003,1.110323
97,22/03/2022,19:30:00,1102600003,1104800000,1096000000,1101640600,1.730805
98,22/03/2022,20:30:00,1102000000,1104495000,1096500000,1103999700,1.808359
99,22/03/2022,21:30:00,1103999700,1105000000,1098520000,1100111311,1.425036
100,22/03/2022,22:30:00,1103767750,1103767750,1097000000,1098000000,0.546444
101,22/03/2022,23:30:00,1097999999,1101335000,1096560200,1097100000,1.101038
102,23/03/2022,00:30:00,1097099999,1101321666,1095000000,1096000000,1.146557
103,23/03/2022,01:30:00,1096065360,1101666000,1094200000,1101334900,0.451530
104,23/03/2022,02:30:00,1100000000,1101664000,1096750000,1097000000,0.435126
105,23/03/2022,03:30:00,1097000000,1099169100,1090000000,1090001000,1.679193
106,23/03/2022,04:30:00,1090001000,1091000000,1085000000,1088200000,2.993420
107,23/03/2022,05:30:00,1088200000,1098000000,1088010000,1097309890,1.459090
108,23/03/2022,06:30:00,1094800000,1101666000,1094800000,1096000000,2.122199
109,23/03/2022,07:30:00,1096000000,1099309000,1094555555,1096909010,1.405314
110,23/03/2022,08:30:00,1096899808,1105000000,1095700100,1097209026,1.995118
111,23/03/2022,09:30:00,1097319200,1101617750,1095000000,1095600000,1.676036
112,23/03/2022,10:30:00,1095600000,1100000100,1095000000,1097700000,0.875109
113,23/03/2022,11:30:00,1097699500,1097699500,1093000115,1093000121,0.937554
114,23/03/2022,12:30:00,1093000121,1103000000,1093000115,1099999999,1.759597
115,23/03/2022,13:30:00,1098999477,1101000000,1095400000,1099999999,1.637740
116,23/03/2022,14:30:00,1099999999,1104987654,1099999999,1103000000,1.761584
117,23/03/2022,15:30:00,1103000000,1108999995,1103000000,1105500000,4.755609
118,23/03/2022,16:30:00,1105000205,1105500000,1093200000,1094400099,3.655849
119,23/03/2022,17:30:00,1093200000,1098999899,1089000000,1093997700,4.519662
120,23/03/2022,18:30:00,1093997700,1102100000,1093109950,1102100000,1.969265
121,23/03/2022,19:30:00,1095200002,1102000000,1091500101,1100993700,1.525280
122,23/03/2022,20:30:00,1100894330,1100993800,1097700000,1099999998,0.923696
123,23/03/2022,21:30:00,1099999998,1101000000,1098000000,1100000000,1.113585
124,23/03/2022,22:30:00,1101000000,1102100000,1098000000,1101999000,1.131830
125,23/03/2022,23:30:00,1100196000,1109000000,1097800001,1105160111,3.673376
126,24/03/2022,00:30:00,1105160110,1111111111,1098800099,1102000000,4.295798
127,24/03/2022,01:30:00,1102000000,1108999800,1100031540,1104205106,0.712450
128,24/03/2022,02:30:00,1107500000,1109000000,1104205006,1105112809,0.981471
129,24/03/2022,03:30:00,1105112809,1108799900,1102100301,1105300000,0.942466
130,24/03/2022,04:30:00,1106000000,1110800000,1105000000,1107091000,1.811770
131,24/03/2022,05:30:00,1107091000,1118899700,1107091000,1116504498,3.954085
132,24/03/2022,06:30:00,1116504498,1118000000,1107109703,1113000011,6.666874
133,24/03/2022,07:30:00,1113000100,1116000000,1111000101,1111888888,2.620752
134,24/03/2022,08:30:00,1112000000,1116000000,1112000000,1115980000,2.547960
135,24/03/2022,09:30:00,1115980000,1115980000,1112000000,1112500000,1.882094
136,24/03/2022,10:30:00,0,0,0,0,0.000000
137,24/03/2022,11:30:00,0,0,0,0,0.000000
138,24/03/2022,12:30:00,0,0,0,0,0.000000
139,24/03/2022,13:30:00,0,0,0,0,0.000000
140,24/03/2022,14:30:00,0,0,0,0,0.000000
141,24/03/2022,15:30:00,0,0,0,0,0.000000
142,24/03/2022,16:30:00,0,0,0,0,0.000000
143,24/03/2022,17:30:00,0,0,0,0,0.000000
144,24/03/2022,18:30:00,0,0,0,0,0.000000
145,25/03/2022,18:30:00,0,0,0,0,0.000000